apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-ebpf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor-ebpf
  template:
    metadata:
      labels:
        app: order-processor-ebpf
    spec:
      containers:
      - name: order-processor-ebpf
        image: 104013952213.dkr.ecr.eu-north-1.amazonaws.com/tracey-reloaded-ebpf:order-processor-ebpf
        ports:
        - containerPort: 8080
        env:
          - name: KUBE_NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: OTEL_HOST
            value: "$(KUBE_NODE_NAME):4317"
---
apiVersion: v1
kind: Service
metadata:
  name: order-processor
spec:
  selector:
    app: order-processor-ebpf
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080