FROM python:3.9

# Set metadata labels for best practices
LABEL authors="Aharon Shahar"
LABEL org.opencontainers.image.name="Tracey Reloaded - Order Processor - for ebpf testing"
LABEL org.opencontainers.image.description="Order Processor for Tracey Reloaded"
LABEL org.opencontainers.image.source="https://github.com/georgep1ckers/tracey-reloaded"

WORKDIR /app

COPY . .

RUN pip install flask \
                psycopg2-binary

CMD ["python", "order-processor.py"]